version: "3.3"

services:
  app:
    build:
      context: "./app"
      args:
        options: --reload
    volumes:
      - ./app/:/app/
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: "mysql+mysqlconnector://root:password@database:3306/exercise"
      CACHE_URI: "redis://cache:6379"
  cache:
    image: redis:7
    tmpfs:
      - /data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      start_period: 5s
      retries: 3
  database:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exercise
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 1s
      timeout: 10s
      retries: 30
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
